### ISSUE TITLE
Getting an error when trying to generate a certificate with --webroot

### ISSUE THREAD

**Issue by galloaleonardo** [zerossl/zerossl-bot#7]
I'm trying to run:
`sudo certbot-zerossl certonly --webroot -d mydomain.com -d www.mydomain.com --zerossl-api-key MY_API_KEY_HERE`

But I got the error:
```
2020-12-16 16:55:13,122:DEBUG:certbot._internal.main:certbot version: 1.10.1
2020-12-16 16:55:13,122:DEBUG:certbot._internal.main:Arguments: ['--preconfigured-renewal']
2020-12-16 16:55:13,122:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#ngi$
2020-12-16 16:55:13,133:DEBUG:certbot._internal.log:Root logging level set at 20
2020-12-16 16:55:13,133:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-12-16 16:55:13,134:DEBUG:certbot._internal.plugins.selection:Requested authenticator None and installer None
2020-12-16 16:55:13,140:DEBUG:certbot.plugins.util:Failed to find executable apache2ctl in PATH: /snap/certbot/793/bin:/snap/certbot/793/usr/bin:/usr/local/s$
2020-12-16 16:55:13,140:DEBUG:certbot._internal.plugins.disco:No installation (PluginEntryPoint#apache): Cannot find Apache executable apache2ctl
Traceback (most recent call last):
  File "/snap/certbot/793/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 157, in prepare
    self._initialized.prepare()
  File "/snap/certbot/793/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 317, in prepare
    self._verify_exe_availability(self.option("ctl"))
  File "/snap/certbot/793/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 434, in _verify_exe_availability
    raise errors.NoInstallationError(
certbot.errors.NoInstallationError: Cannot find Apache executable apache2ctl
2020-12-16 16:55:13,140:DEBUG:certbot._internal.plugins.disco:No installation (PluginEntryPoint#nginx): Could not find a usable 'nginx' binary. Ensure nginx $
Traceback (most recent call last):
  File "/snap/certbot/793/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 157, in prepare
    self._initialized.prepare()
  File "/snap/certbot/793/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 185, in prepare
    raise errors.NoInstallationError(
certbot.errors.NoInstallationError: Could not find a usable 'nginx' binary. Ensure nginx exists, the binary is executable, and your PATH is set correctly.
2020-12-16 16:55:13,141:DEBUG:certbot._internal.plugins.selection:No candidate plugin
2020-12-16 16:55:13,141:DEBUG:certbot._internal.plugins.selection:Selected authenticator None and installer None
```

It looks like the `Apache` and `Nginx` plugin is missing, but I don't need them. I'm just wanting to generate the certificate.

OS: Ubuntu 16.04
I installed the certbot with snap, as shown on the official website.

**Comment by galloaleonardo** [comment]
The same with `--standalone`.

**Comment by Blackbam** [comment]
@galloaleonardo Is this still a problem?

**Comment by Blackbam** [comment]
Closed as no further reaction.
